INSERT INTO PRODUCT(CODE,NAME,DESCRIPTION,UNITS,PRICE)
VALUES ('001','Libro de C#','Aprende C# en minutos',20,25.500);

INSERT INTO PRODUCT(CODE,NAME,DESCRIPTION,UNITS,PRICE)
VALUES ('002','Libro de PostgreSQL','Aprende PSQL en minutos',50,30.850);

INSERT INTO PRODUCT(CODE,NAME,DESCRIPTION,UNITS,PRICE)
VALUES ('003','Libro de UX','Aprende UX en minutos',2,3.850);

INSERT INTO CUSTOMER (IDENTIFICAION,FULLNAME,BIRTH)
VALUES ('123456','Pepito Perez','1990-10-10');

INSERT INTO CUSTOMER (IDENTIFICAION,FULLNAME,BIRTH)
VALUES ('123457','Billie Joe Amstrong','1991-08-10');

INSERT INTO BILL (DESCRIPTION,CUSTOMER_ID,TOTAL_PRICE)
VALUES ('Primera Factura',5,5.500);

INSERT INTO BILL (DESCRIPTION,CUSTOMER_ID,TOTAL_PRICE)
VALUES ('Segunda Factura',6,30.500);

INSERT INTO BILL_DETAIL (BILL_ID,PRODUCT_ID,COUNT,PRICE)
VALUES (5,10,2,50.500);

INSERT INTO BILL_DETAIL (BILL_ID,PRODUCT_ID,COUNT,PRICE)
VALUES (6,11,2,55.580);
